Update cron to run every hour.
govCMS/govcms8-scaffold pull request #26
Opened 2019-10-16 08:23 UTC by steveworley

- Changes root directory to /app in case the working dir of the cron pod changes.
- Updates cron to run hourly.

2019-10-16 09:13 UTC, AlexSkrypnyk commented
@steveworley Could you please explain (for historical purposes) when would "Changes root directory to /app in case the working dir of the cron pod changes." happen. If it is not too hard. Thanks

2019-10-18 01:05 UTC, steveworley commented
We've noticed that sometimes k8s doesn't attach to `/app` when it's creating the cron pods, because Drush launcher is now included and there are multiple versions of drush if you execute `drush cron` outside of `/app` you get a different Drush installation and the docroot is not `/app` so it doesn't know how to run cron and throws a fatal error.

2019-10-18 02:21 UTC, AlexSkrypnyk approved these changes

2019-10-18 04:48 UTC, stooit requested changes
Can we actually split this into 2 PRs?

1) Immediate requirement: pass in `--root` flag
2) Secondary requirement: Tweak to run hourly (may need communication, suggested that we should do scheduled publishing every 15m and full cron hourly)

2019-10-18 04:57 UTC, stooit approved these changes

2019-10-18 04:58 UTC, merged